### PR TITLE
add bevy feature for NavVec3⟷Vec3 conversion

### PR DESCRIPTION
**Pull request by Anshorei**

### CODE REVIEW

**Comment by PsichiX** [comment]
hi! could you explain to me why you think this change should belong to this crate?
from my point of view, including a big and very specific dependency just for the sake of type conversion is undesirable - i could add `mint` for making general types conversion because `mint` is made to solve exactly this problem, but neither me nor users would like to pull a whole game engine just because it offers built-in type conversion for that engine.

**Comment by Anshorei** [comment]
That's why I added it as an optional dependency.

That said if `mint` offers a more general solution that would be fine too, I had not heard about mint before.

**Comment by PsichiX** [comment]
great, so i'll add mint and try to upgrade dependencies (they minght be pretty old at this moment)

**Comment by PsichiX** [comment]
@Anshorei new version with `mint` integration and deps upgrade has got published, i hope that will work for your bevy plugin :D
closing PR :)

**Pull request closed without merging**
